# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  icubetrain:
    image: icubetrain
    build:
      context: .
      dockerfile: src/iCubeTrain/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
