# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'

networks:
  icubetrain-network:

services:
  frontend:
    build:
      context: ./frontend/iCubeTrain-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/iCubeTrain-app:/app
    depends_on:
      - icubetrain
    networks:
      - icubetrain-network

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8000:8080
    depends_on:
      - icubetrain
    environment:
      - SWAGGER_JSON=/swagger/v1/swagger.json
    volumes:
      - ./swagger/v1/swagger.json:/swagger/v1/swagger.json
    networks:
      - icubetrain-network

  mssqldb:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=user1@password1 
    ports:
      - "8002:1433"
    networks:
      - icubetrain-network

  ftp:
    container_name: ftp
    image: fauria/vsftpd # Or your preferred FTP server image
    environment:
      - FTP_USER=user1
      - FTP_PASS=user1
      - PASV_ADDRESS=127.0.0.1
    ports:
      - "8003:21"
    volumes:
      - ~/ftpdata:/home/vsftpd
    networks:
      - icubetrain-network

  icubetrain:
    container_name: icubetrain
    image: icubetrain
    build:
      context: .
      dockerfile: src/iCubeTrain/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - mssqldb
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssqldb;Database=iCubeTrainDb;User Id=sa;Password=user1@password1;TrustServerCertificate=True;
    networks:
      - icubetrain-network
